### ISSUE TITLE
route command not found during install

### ISSUE THREAD

**Issue by JSnetSystems** [moshix/zlinux#5]
After entering the password step during the install, "./script/set_netowrk: line 22: route: command not found" message appears

Interface    will be setup for zLinux internet access...
Bad argument `10.1.1.0/24'
Try `iptables -h' or 'iptables --help' for more information.
Starting hercules with installation script now. Be patient

[zlinux install.txt](https://github.com/moshix/zlinux/files/9173927/zlinux.install.txt)

manually installing net-tools on my local machine and restarting the install resolved the error message.

now seeing message "nterface  ens33  will be setup for zLinux internet access..." after restarting the install.

**Comment by moshix** [comment]
Pls make sure you have the route command installed. The package net-tools has it. The script now checks for it's availability and gives an error message if not present. Closing this issue.
