### ISSUE TITLE
Prebuilt hyperion and utils fail to run on an older CPU

### ISSUE THREAD

**Issue by rjpontefract** [moshix/zlinux#6]
Thanks for the automated install and the YouTube videos, very enjoyable and informative.
During install I found that dasdinit64 and hercules fail with an illegal instruction:

```
$ ./dasdinit64
Illegal instruction (core dumped)
```

```
$ ./hercules

    +++ OOPS! +++

Hercules has crashed! (Illegal instruction)
```

The CPU is as follows:

```
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 45
model name      : Intel(R) Xeon(R) CPU E5-2680 0 @ 2.70GHz
stepping        : 7
microcode       : 0x71a
cpu MHz         : 2693.509
cache size      : 20480 KB
```

I rebuilt hercules using the included script and the new version works fine.

**Comment by spike999uk** [comment]
Thanks for this. Just spent 30 mins chasing this very issue but in my case was running on Ubuntu server 20.04. Getting the same error. Will rebuild hercules as you have done and see if that works.

**Comment by moshix** [comment]
thank you both. The hyperion we supply is built on a machiene too new, with a compiler too new. We are currently building a hyperion on Intel Duo processor which should then make it possible to run this hyperion on all x86-64 type processors. Stay tuned, and thanks for reporting.

**Comment by moshix** [comment]
There are now a whole new set of binaries, built for much wider modern CPU compatibility. 

Closing this one for now. Feel free to re-open if you find new issues.
